/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobId = IDL.Nat;
export const Time = IDL.Int;
export const FileName = IDL.Text;
export const PrinterName = IDL.Text;
export const Priority = IDL.Nat;
export const PrintJob = IDL.Record({
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'printing' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  }),
  'submitted' : Time,
  'user' : IDL.Principal,
  'jobId' : JobId,
  'fileName' : FileName,
  'printer' : PrinterName,
  'priority' : Priority,
});
export const PrinterStatus = IDL.Record({
  'status' : IDL.Variant({
    'busy' : IDL.Null,
    'offline' : IDL.Null,
    'online' : IDL.Null,
  }),
  'inkLevel' : IDL.Nat,
  'lastJob' : IDL.Opt(JobId),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelPrintJob' : IDL.Func([JobId], [], []),
  'deleteJob' : IDL.Func([JobId], [], []),
  'getAllJobs' : IDL.Func([], [IDL.Vec(PrintJob)], ['query']),
  'getAllPrinters' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(PrinterName, PrinterStatus))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobQueue' : IDL.Func([], [IDL.Vec(PrintJob)], ['query']),
  'getJobStatus' : IDL.Func([JobId], [PrintJob], ['query']),
  'getJobsByPrinter' : IDL.Func([PrinterName], [IDL.Vec(PrintJob)], ['query']),
  'getJobsByStatus' : IDL.Func(
      [
        IDL.Variant({
          'cancelled' : IDL.Null,
          'printing' : IDL.Null,
          'pending' : IDL.Null,
          'completed' : IDL.Null,
        }),
      ],
      [IDL.Vec(PrintJob)],
      ['query'],
    ),
  'getJobsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(PrintJob)], ['query']),
  'getPrinterJobCount' : IDL.Func([PrinterName], [IDL.Nat], ['query']),
  'getPrinterStatus' : IDL.Func([PrinterName], [PrinterStatus], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPrintJob' : IDL.Func([PrinterName, FileName, Priority], [JobId], []),
  'updateInkLevel' : IDL.Func([PrinterName, IDL.Nat], [], []),
  'updatePrinterStatus' : IDL.Func(
      [
        PrinterName,
        IDL.Variant({
          'busy' : IDL.Null,
          'offline' : IDL.Null,
          'online' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobId = IDL.Nat;
  const Time = IDL.Int;
  const FileName = IDL.Text;
  const PrinterName = IDL.Text;
  const Priority = IDL.Nat;
  const PrintJob = IDL.Record({
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'printing' : IDL.Null,
      'pending' : IDL.Null,
      'completed' : IDL.Null,
    }),
    'submitted' : Time,
    'user' : IDL.Principal,
    'jobId' : JobId,
    'fileName' : FileName,
    'printer' : PrinterName,
    'priority' : Priority,
  });
  const PrinterStatus = IDL.Record({
    'status' : IDL.Variant({
      'busy' : IDL.Null,
      'offline' : IDL.Null,
      'online' : IDL.Null,
    }),
    'inkLevel' : IDL.Nat,
    'lastJob' : IDL.Opt(JobId),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelPrintJob' : IDL.Func([JobId], [], []),
    'deleteJob' : IDL.Func([JobId], [], []),
    'getAllJobs' : IDL.Func([], [IDL.Vec(PrintJob)], ['query']),
    'getAllPrinters' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(PrinterName, PrinterStatus))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobQueue' : IDL.Func([], [IDL.Vec(PrintJob)], ['query']),
    'getJobStatus' : IDL.Func([JobId], [PrintJob], ['query']),
    'getJobsByPrinter' : IDL.Func(
        [PrinterName],
        [IDL.Vec(PrintJob)],
        ['query'],
      ),
    'getJobsByStatus' : IDL.Func(
        [
          IDL.Variant({
            'cancelled' : IDL.Null,
            'printing' : IDL.Null,
            'pending' : IDL.Null,
            'completed' : IDL.Null,
          }),
        ],
        [IDL.Vec(PrintJob)],
        ['query'],
      ),
    'getJobsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(PrintJob)], ['query']),
    'getPrinterJobCount' : IDL.Func([PrinterName], [IDL.Nat], ['query']),
    'getPrinterStatus' : IDL.Func([PrinterName], [PrinterStatus], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPrintJob' : IDL.Func([PrinterName, FileName, Priority], [JobId], []),
    'updateInkLevel' : IDL.Func([PrinterName, IDL.Nat], [], []),
    'updatePrinterStatus' : IDL.Func(
        [
          PrinterName,
          IDL.Variant({
            'busy' : IDL.Null,
            'offline' : IDL.Null,
            'online' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };