/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FileName = string;
export type JobId = bigint;
export interface PrintJob {
  'status' : { 'cancelled' : null } |
    { 'printing' : null } |
    { 'pending' : null } |
    { 'completed' : null },
  'submitted' : Time,
  'user' : Principal,
  'jobId' : JobId,
  'fileName' : FileName,
  'printer' : PrinterName,
  'priority' : Priority,
}
export type PrinterName = string;
export interface PrinterStatus {
  'status' : { 'busy' : null } |
    { 'offline' : null } |
    { 'online' : null },
  'inkLevel' : bigint,
  'lastJob' : [] | [JobId],
}
export type Priority = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelPrintJob' : ActorMethod<[JobId], undefined>,
  'deleteJob' : ActorMethod<[JobId], undefined>,
  'getAllJobs' : ActorMethod<[], Array<PrintJob>>,
  'getAllPrinters' : ActorMethod<[], Array<[PrinterName, PrinterStatus]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobQueue' : ActorMethod<[], Array<PrintJob>>,
  'getJobStatus' : ActorMethod<[JobId], PrintJob>,
  'getJobsByPrinter' : ActorMethod<[PrinterName], Array<PrintJob>>,
  'getJobsByStatus' : ActorMethod<
    [
      { 'cancelled' : null } |
        { 'printing' : null } |
        { 'pending' : null } |
        { 'completed' : null },
    ],
    Array<PrintJob>
  >,
  'getJobsByUser' : ActorMethod<[Principal], Array<PrintJob>>,
  'getPrinterJobCount' : ActorMethod<[PrinterName], bigint>,
  'getPrinterStatus' : ActorMethod<[PrinterName], PrinterStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPrintJob' : ActorMethod<[PrinterName, FileName, Priority], JobId>,
  'updateInkLevel' : ActorMethod<[PrinterName, bigint], undefined>,
  'updatePrinterStatus' : ActorMethod<
    [
      PrinterName,
      { 'busy' : null } |
        { 'offline' : null } |
        { 'online' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];