/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Priority = bigint;
export type Time = bigint;
export type PrinterName = string;
export type FileName = string;
export type JobId = bigint;
export interface PrintJob {
    status: Variant_cancelled_printing_pending_completed;
    submitted: Time;
    user: Principal;
    jobId: JobId;
    fileName: FileName;
    printer: PrinterName;
    priority: Priority;
}
export interface UserProfile {
    name: string;
}
export interface PrinterStatus {
    status: Variant_busy_offline_online;
    inkLevel: bigint;
    lastJob?: JobId;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_busy_offline_online {
    busy = "busy",
    offline = "offline",
    online = "online"
}
export enum Variant_cancelled_printing_pending_completed {
    cancelled = "cancelled",
    printing = "printing",
    pending = "pending",
    completed = "completed"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelPrintJob(jobId: JobId): Promise<void>;
    deleteJob(jobId: JobId): Promise<void>;
    getAllJobs(): Promise<Array<PrintJob>>;
    getAllPrinters(): Promise<Array<[PrinterName, PrinterStatus]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getJobQueue(): Promise<Array<PrintJob>>;
    getJobStatus(jobId: JobId): Promise<PrintJob>;
    getJobsByPrinter(printer: PrinterName): Promise<Array<PrintJob>>;
    getJobsByStatus(status: Variant_cancelled_printing_pending_completed): Promise<Array<PrintJob>>;
    getJobsByUser(user: Principal): Promise<Array<PrintJob>>;
    getPrinterJobCount(printer: PrinterName): Promise<bigint>;
    getPrinterStatus(printer: PrinterName): Promise<PrinterStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitPrintJob(printer: PrinterName, fileName: FileName, priority: Priority): Promise<JobId>;
    updateInkLevel(printer: PrinterName, inkLevel: bigint): Promise<void>;
    updatePrinterStatus(printer: PrinterName, status: Variant_busy_offline_online): Promise<void>;
}
import type { FileName as _FileName, JobId as _JobId, PrintJob as _PrintJob, PrinterName as _PrinterName, PrinterStatus as _PrinterStatus, Priority as _Priority, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelPrintJob(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelPrintJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelPrintJob(arg0);
            return result;
        }
    }
    async deleteJob(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async getAllJobs(): Promise<Array<PrintJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPrinters(): Promise<Array<[PrinterName, PrinterStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrinters();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrinters();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobQueue(): Promise<Array<PrintJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobQueue();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobQueue();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobStatus(arg0: JobId): Promise<PrintJob> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobStatus(arg0);
                return from_candid_PrintJob_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobStatus(arg0);
            return from_candid_PrintJob_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByPrinter(arg0: PrinterName): Promise<Array<PrintJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByPrinter(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByPrinter(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByStatus(arg0: Variant_cancelled_printing_pending_completed): Promise<Array<PrintJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByStatus(to_candid_variant_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByStatus(to_candid_variant_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByUser(arg0: Principal): Promise<Array<PrintJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByUser(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByUser(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrinterJobCount(arg0: PrinterName): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrinterJobCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrinterJobCount(arg0);
            return result;
        }
    }
    async getPrinterStatus(arg0: PrinterName): Promise<PrinterStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrinterStatus(arg0);
                return from_candid_PrinterStatus_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrinterStatus(arg0);
            return from_candid_PrinterStatus_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitPrintJob(arg0: PrinterName, arg1: FileName, arg2: Priority): Promise<JobId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPrintJob(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPrintJob(arg0, arg1, arg2);
            return result;
        }
    }
    async updateInkLevel(arg0: PrinterName, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInkLevel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInkLevel(arg0, arg1);
            return result;
        }
    }
    async updatePrinterStatus(arg0: PrinterName, arg1: Variant_busy_offline_online): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrinterStatus(arg0, to_candid_variant_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrinterStatus(arg0, to_candid_variant_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_PrintJob_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrintJob): PrintJob {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PrinterStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrinterStatus): PrinterStatus {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobId]): JobId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        busy: null;
    } | {
        offline: null;
    } | {
        online: null;
    };
    inkLevel: bigint;
    lastJob: [] | [_JobId];
}): {
    status: Variant_busy_offline_online;
    inkLevel: bigint;
    lastJob?: JobId;
} {
    return {
        status: from_candid_variant_n11(_uploadFile, _downloadFile, value.status),
        inkLevel: value.inkLevel,
        lastJob: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.lastJob))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        cancelled: null;
    } | {
        printing: null;
    } | {
        pending: null;
    } | {
        completed: null;
    };
    submitted: _Time;
    user: Principal;
    jobId: _JobId;
    fileName: _FileName;
    printer: _PrinterName;
    priority: _Priority;
}): {
    status: Variant_cancelled_printing_pending_completed;
    submitted: Time;
    user: Principal;
    jobId: JobId;
    fileName: FileName;
    printer: PrinterName;
    priority: Priority;
} {
    return {
        status: from_candid_variant_n6(_uploadFile, _downloadFile, value.status),
        submitted: value.submitted,
        user: value.user,
        jobId: value.jobId,
        fileName: value.fileName,
        printer: value.printer,
        priority: value.priority
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_PrinterName, _PrinterStatus]): [PrinterName, PrinterStatus] {
    return [
        value[0],
        from_candid_PrinterStatus_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    busy: null;
} | {
    offline: null;
} | {
    online: null;
}): Variant_busy_offline_online {
    return "busy" in value ? Variant_busy_offline_online.busy : "offline" in value ? Variant_busy_offline_online.offline : "online" in value ? Variant_busy_offline_online.online : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    printing: null;
} | {
    pending: null;
} | {
    completed: null;
}): Variant_cancelled_printing_pending_completed {
    return "cancelled" in value ? Variant_cancelled_printing_pending_completed.cancelled : "printing" in value ? Variant_cancelled_printing_pending_completed.printing : "pending" in value ? Variant_cancelled_printing_pending_completed.pending : "completed" in value ? Variant_cancelled_printing_pending_completed.completed : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PrintJob>): Array<PrintJob> {
    return value.map((x)=>from_candid_PrintJob_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_PrinterName, _PrinterStatus]>): Array<[PrinterName, PrinterStatus]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cancelled_printing_pending_completed): {
    cancelled: null;
} | {
    printing: null;
} | {
    pending: null;
} | {
    completed: null;
} {
    return value == Variant_cancelled_printing_pending_completed.cancelled ? {
        cancelled: null
    } : value == Variant_cancelled_printing_pending_completed.printing ? {
        printing: null
    } : value == Variant_cancelled_printing_pending_completed.pending ? {
        pending: null
    } : value == Variant_cancelled_printing_pending_completed.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_busy_offline_online): {
    busy: null;
} | {
    offline: null;
} | {
    online: null;
} {
    return value == Variant_busy_offline_online.busy ? {
        busy: null
    } : value == Variant_busy_offline_online.offline ? {
        offline: null
    } : value == Variant_busy_offline_online.online ? {
        online: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
